[phases.setup]
nixpkgsArchive = "https://github.com/NixOS/nixpkgs/archive/nixpkgs-23.05.tar.gz"

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npx prisma generate", "npx prisma migrate deploy"]

[start]
cmd = "npm run start"
